development:
  dialect: "mysql"
  database: "gorm_test_development"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  encoding: "utf8mb4_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(127.0.0.1:3306)/gorm_test_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(127.0.0.1:3306)/gorm_test_production?parseTime=true&multiStatements=true&readTimeout=1s"}}